dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install nbfancy

script:
  - nbfancy init --include none
  - nbfancy rerun
  - nbfancy render
  - nbfancy html

deploy:
  provider: pages
  repo: vickyscowcroft/teaching_dev
  target-branch: gh-pages
  local-dir: gh-pages/html
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master